### PR TITLE
Job file additions

### PR DESCRIPTION
**Pull request by CanyonCasa**
Changed commandline interface to automaticallly build a job file if only
-j with no filename is specified. Fixed the configDefaults.json file
that was missing defaults from pluggins. Updated README.md file with
more detailed Job File section. Fixed setTime.js pluggin that was
incorrectly referencing ExamplePlugin. Also noted that ExamplePluggin
presently gets loaded, which is probably not expected. but not certain
what action to take.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great - thanks! I'm not sure having ExamplePlugin loaded as a big deal - but it's good to be aware of anyway :)

**Comment by gfwilliams** [comment]
I'll have to merge this manually as it conflicts with what's there already so I won't do it right now - I think it might be because you didn't `git pull` before you made the new changes, and I'd already taken yours in but updated the CLI's `--help` message to match the README

**Comment by gfwilliams** [comment]
Looks like somehow this has got a whole bunch of merge errors committed in (the duplicates and lines containing `<<<<<<<`, `=======`, and `>>>>>>`) - I guess that could have been me - not sure. Any chance you could try and fix those?

**Comment by CanyonCasa** [comment]
I probably messed it up on my end. I'm used to Perforce and just learning how different it works than Git. I was trying to update to your latest repo and create a new pull request that would be less work for you. Appearantly the last pull I synced to my repo and didn't get other changes you made.  You can cancel the pull request and I'll issue a new one once I get things synced up with your repo.

**Comment by CanyonCasa** [comment]
Ok it looks like the README.md and bin/espruino-cli.js files are clean now and can be pulled now without conflict. I assume since Git does not give me a Create New Pull Request button that the open one takes care of it. If not just let me know what you need me to do. Sorry for the whole screw up here.

**Comment by gfwilliams** [comment]
Ok, thanks! Looks good - although it's got a lot of changes in that I thought were already in GitHub. It should figure them out when it merges anyway :)

**Comment by gfwilliams** [comment]
Hmm. I could be wrong but it looks like the only real change here is to revert the changes to the docs that I put in?

```
diff --git a/README.md b/README.md
index 98069d2..0a19815 100644
--- a/README.md
+++ b/README.md
@@ -15,7 +15,7 @@ When installed as a Node module with `npm install -g espruino` you get a command
 USAGE: espruino ...options... [file_to_upload.js]
 
   -h,--help                : Show this message
-  -j [job.json]            : Make or load options from JSON 'job file' section
+  -j [job.json]            : Make or load options from JSON job file - See Job File.
   -c,--color               : Color mode,
   -v,--verbose             : Verbose
   -q,--quiet               : Quiet - apart from Espruino output
@@ -36,7 +36,7 @@ USAGE: espruino ...options... [file_to_upload.js]
   -e command               : Evaluate the given expression on Espruino
                                If no file to upload is specified but you use -e,
                                Espruino will not be reset
-#
+
 If no file, command, or firmware update is specified, this will act
 as a terminal for communicating directly with Espruino. Press Ctrl-C
 twice to exit.
diff --git a/bin/espruino-cli.js b/bin/espruino-cli.js
index 21cf4e5..cbe9c9b 100755
--- a/bin/espruino-cli.js
+++ b/bin/espruino-cli.js
@@ -143,7 +143,7 @@ if (args.help) {
  ["USAGE: espruino ...options... [file_to_upload.js]",
   "",
   "  -h,--help                : Show this message",
-  "  -j job.json              : Load options from JSON job file - see configDefaults.json for example",
+  "  -j [job.json]            : Make or load options from JSON job file - See Job File.",
   "  -v,--verbose             : Verbose",
   "  -q,--quiet               : Quiet - apart from Espruino output",
   "  -m,--minify              : Minify the code before sending it",
```

Basically there's no point saying `See Job File` in the help provided by running the CLI with `--help` - it doesn't make any sense.

Sorry - reverting this... Not sure what happened here but it looks like I committed the changes onto the wrong branch so you weren't working with the most up to date version.

**Pull request merged**
