### PR TITLE
Created sendCode API, made it possible to use NPM modules via CLI

### PR DESCRIPTION
**Pull request by chalkers**
[x] esp.sendCode
[x] branched logic for Node usage of NPM
[x] removed deprication warning on serial port

### CODE REVIEW

**Comment by chalkers** [comment]
@gfwilliams also bumped the version number :)

**Comment by gfwilliams** [comment]
Just wondered - why are you using the tar.gz package when on node? Does this add something that the pre-packaged one doesn't? I mean, otherwise it's just duplicated  code and added dependencies... Next time someone wants to make a change to npmModules you're pretty much guaranteed it's going to break either the node version or the browser version?

**Comment by chalkers** [comment]
I first attempted swapping out in the TarGZ module the `XMLHttpRequest` with a "Node compatible" version. When I did the TarGZ function was saying that the gz file wasn't a valid format. The existing TarGZ didn't have a clean API for me to hook into. That's when I moved to using another dependency, using a more "modern" `request` module for parsing streams coming in.

**Comment by gfwilliams** [comment]
:( That's a shame - I guess it might have been tidier. Could be a UTF8 issue? Those always get me :)

Thanks for trying anyway...

**Pull request merged**
